### ISSUE TITLE
Feature request: LiDAR info capture

### ISSUE THREAD

**Issue by bundle-adjuster** [Varvrar/ios_logger#12]
Hi @Varvrar,

Thank you so much for the app. Is there any way we can capture LiDAR information as well? If so could you point me to the direction of how you would go about it?

**Comment by Varvrar** [comment]
Hello!

I didn't work with LiDAR info, bui I think you should change AVCaptureSession input and output.
Check apple articles and code samples about depth data capture: [link](https://developer.apple.com/documentation/avfoundation/additional_data_capture?language=objc)
