### ISSUE TITLE
Is it possible to collect afaceanchor.blendshapelocation?

### ISSUE THREAD

**Issue by dev-screening** [Varvrar/ios_logger#3]
Is it possible to collect [arfaceanchor.blendshapelocation](https://developer.apple.com/documentation/arkit/arfaceanchor/blendshapelocation) data using your app?

**Comment by Varvrar** [comment]
Hello!
This app using ARKit only for logging device poses (ARKit>ARFrame>ARCamera>transform).
Of cource you can modify it for collecting another data.
