### ISSUE TITLE
Could ios_logger record the timestamp of imu and camera data respectively ?

### ISSUE THREAD

**Issue by baaixw** [Varvrar/ios_logger#5]
thanks for your incredible work, your great work would  help me a lot in my research.
I want to know, could ios_logger record the timestamp of imu and camera data respectively ?
thank you very much in advance.

**Comment by Varvrar** [comment]
Thanks for the flattering review.

I didn't quite understand the question... 
Every camera frame recorded with timestamp: the frame is compressed into the video and its timestamp puts into Frames.txt.
Each imu measurement (accelerometer, gyroscope, etc.) also puts in log files with timestamp

**Comment by baaixw** [comment]
> Thanks for the flattering review.
> 
> I didn't quite understand the question...
> Every camera frame recorded with timestamp: the frame is compressed into the video and its timestamp puts into Frames.txt.
> Each imu measurement (accelerometer, gyroscope, etc.) also puts in log files with timestamp

Thanks for your kindly reply. I got it.
